### ISSUE TITLE
support CSS inlining

### ISSUE THREAD

**Issue by FelixSchwarz** [FelixSchwarz/mjml-stub#1]
It would be nice to support CSS inlining (similar to mjml upstream). There are some Python libraries which might be helpful:

- [premailer](https://github.com/peterbe/premailer), 3-clause BSD, recent commits
- [inlinestyler](https://github.com/dlanger/inlinestyler), 3-clause BSD, last commit March 2018
- [pynliner](https://github.com/rennat/pynliner), MIT license, last commit January 2017

Based on the number of github stars, forks I guess premailer seems to be the most popular library.

**Comment by caseyjhol** [comment]
https://github.com/Stranger6667/css-inline seems promising.

**Comment by FelixSchwarz** [comment]
Closed via 611f7f013aea15147916117242593b59b3153ef8 and cc1b3447c69bd20dd98a3d741d2bdf8ee1c631c5.

We can also support other css inlining libraries in the future if someone wants to add support for that. In particular I could imagine having a pure-python implementation could be nice. However "css_inline" looks ok for now so I won't add support for premailer in the near tearm.
