### ISSUE TITLE
Add json format support

### ISSUE THREAD

**Issue by pcorpet** [FelixSchwarz/mjml-stub#12]
The javascript version of mjml handles [json MJML](https://documentation.mjml.io/#using-mjml-in-json) both as input (if you give a dict to the `mjml2html` function) and as an output (in a `json` field).

Before sending you a PR:
 * is it OK to add this feature?
 * for input, the API is not exactly the same as in js (python accepts a file descriptor, whereas js gets a string), is it OK to accept a dict for json-like format?

**Comment by FelixSchwarz** [comment]
Thank you for sending the PR.

> - is it OK to add this feature?
> - for input, the API is not exactly the same as in js (python accepts a file descriptor, whereas js gets a string), is it OK to accept a dict for json-like format?

I was not aware of json MJML but if you need this we can add it of course.

Also I don't think we need bug-for-bug compatibility. The Python implementation should be reasonably similar but we can change the details to make the API easier to use in Python.

I'll look at your bug report later today - it's a very busy time here.

**Comment by FelixSchwarz** [comment]
closed by #13 (but I'd appreciate a response regarding hiding children)
