### ISSUE TITLE
Add support for custom components

### ISSUE THREAD

**Issue by caseyjhol** [FelixSchwarz/mjml-stub#29]
We should add the ability to create and register custom components (as well as the ability to extend existing components).

https://documentation.mjml.io/#creating-a-component

**Comment by FelixSchwarz** [comment]
Agreed, this is would be helpful.

**Comment by caseyjhol** [comment]
I might try to get a start on this today - did you have any thoughts already on how you'd like to see this implemented?

**Comment by FelixSchwarz** [comment]
implemented 4ce237628dbb9a8877add8e780b094e483f47cfc
