### ISSUE TITLE
HTML entities such us &nbsp; or &copy; are not supported

### ISSUE THREAD

**Issue by barsch** [FelixSchwarz/mjml-stub#6]
currently fails with:

```lxml.etree.XMLSyntaxError: Entity 'copy' not defined, line 853, column 19```

see also:
https://stackoverflow.com/questions/31210655/nbsp-text-not-handled-by-the-lxml

**Comment by FelixSchwarz** [comment]
Yup, should be handled but isn't. Contributions welcome :-)
